### ISSUE TITLE
Add several tags to the resource group

### ISSUE THREAD

**Issue by thefeds-nau** [russmckendrick/DevOpsAnsiblePipeline#1]
Hello and thank you for this repo. I have been successful in using it, but I wanted to find out how I could add the 18 tags and values my tenant requires? any assistance would be greatly appreciated.
Thank you
Fed

**Comment by thefeds-nau** [comment]
Figured it out!

**Comment by russmckendrick** [comment]
Hey Fed, sorry for the delayed response, I am glad you figured it out and also that you have found it useful. Russ
